NITROGENOUS_BASE = ["A", "T", "C", "G"]
SEQUENCE_SIZE = 4
SEQUENCE_TIMES = 2
SEQUENCE = [
    NITROGENOUS_BASE[0] * SEQUENCE_SIZE,
    NITROGENOUS_BASE[1] * SEQUENCE_SIZE,
    NITROGENOUS_BASE[2] * SEQUENCE_SIZE,
    NITROGENOUS_BASE[3] * SEQUENCE_SIZE,
]
